version: '3.9'

services:
  database:
    image: 'postgres:latest'
    restart: always
    container_name: ${HOST}
    networks:
      - rede-virtual-2
    ports:
      - '5432:5432'
    volumes:
      - ./data/dataBase:/data/dataBase
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USERNAME: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
networks:
  rede-virtual-2: